### PR TITLE
Merge pull request #1 from TheTorProject/master

### PR DESCRIPTION
**Pull request by TylerJFisher**
Update from upstream

### CODE REVIEW

**Comment by TylerJFisher** [comment]
Hm. I was trying to update TylerJFisher:master but it looks like I accidentally updated TheTorProject:master - I'll revert this.

**Comment by vyp** [comment]
Can't you just pull/fetch from a 'https://github.com/TheTorProject/ooni-api' remote?

**Comment by TylerJFisher** [comment]
I'm not familiar with the process of updating forks in the GitHub UI and didn't notice that I was on the wrong repository page. I am a very dangerous person, etc, etc.

**Comment by vyp** [comment]
Ah same, I don't know if it is even possible (is it?). But of course you can always just use plain git.

**Comment by TylerJFisher** [comment]
Yeah, IIRC you go to your forked repository page, and issue a pull request to the original repository - I made the mistake of being on the original repository page as opposed to the forked repository page, and didn't realize it.

I could use plain git, yeah. 

I don't think that a mistake like this is a huge deal though, personally.

**Comment by vyp** [comment]
No of course not, just trying to help, is all. :) I think with git fetching/pulling and then pushing, it doesn't leave weird things like "This branch is 1 commit ahead, 4 commits behind TheTorProject:master." on your fork even though there's no actual difference (because it wouldn't have your merge commits).

Maybe github should provide an easy github ui way to do this that doesn't involve having merge commits, not sure.

**Pull request closed without merging**
