### PR TITLE
Feature/routes api fix

### PR DESCRIPTION
**Pull request by hellais**
This is based on top of the work done by @simonv3.

What I have in mind is to for the moment just implement a very simplistic GUI to the reports that doesn't even operate on presenting the anomalies. We should implement that in a second iteration of this once @TylerJFisher @guyhughes and I implement those as postgres stored procedures.

There is a staging database that has some partial measurement data that you should have access to.

In order to use it I recommend you edit `server/datasources.development.js` to look something like:

```
module.exports = {
  "db": {
    "host": "52.70.253.177",
    "port": "5432",
    "database": "ooni_pipeline",
    "username": "ooni",
    "password": "XXXXXXXXX",
    "name": "postgres",
    "debug": true,
    "connector": "postgresql",
    "ssl": true
  },
  "mem": {
    "name": "mem",
    "connector": "memory"
  }
}
```

### CODE REVIEW

**Comment by TylerJFisher** [comment]
@hellais This looks fantastic - and I'll definitely +2 this pull request. Thank you for getting this pushed through so quickly - once this PR is integrated, we should be able to do quite a bit with regards to the MvP in the next two weeks.

**Comment by simonv3** [comment]
:+1: this looks great - thanks for doing this @hellais

**Comment by TylerJFisher** [comment]
In server/boot/create-fixtures.js why do we need to create dummy data? Shouldn't that be accessible from the staging DB now? Was that included to get by the loading screen?

**Comment by simonv3** [comment]
@TylerJFisher I haven't pulled this PR down, but this is what I was talking about in the meeting - the fixtures present the current data, and connecting to the staging just hangs. Hellias mentioned in the meeting that his push to this branch gets started with the new data model.

**Comment by hellais** [comment]
I implemented the API endpoints for the list of vendors and for the list of blocked URLs here: https://github.com/TheTorProject/ooni-api/commit/4c6590f9bc15549ef1fa191167c3c1c60421580e.

**Comment by simonv3** [comment]
These look great. Thanks.

**Pull request merged**
